version: "3.9"

services:
  backend:
    build: ./BackEnd
    container_name: collegegram-backend
    restart: unless-stopped
    env_file:
      - ./BackEnd/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app-network


  postgres:
    image: postgres:15
    container_name: collegegram-db
    restart: unless-stopped
    # environment:
    #   POSTGRES_USER: ${DB_USER}
    #   POSTGRES_PASSWORD: ${DB_PASS}
    #   POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    env_file:
      - ./BackEnd/.env

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge